void main()
{
  List<Map<String,dynamic>> studentData=[
    {
      "name":"prachi",
      "grid":3674,
      "age":17,
      "city":"surat",
    },
    {
      "name":"ruhi",
      "grid":3675,
      "age":19,
      "city":"los angeles",
    },
    {
      "name":"kunjal",
      "grid":3676,
      "age":19,
      "city":"mumbai",
    },
    {
      "name":"prathna",
      "grid":3677,
      "age":19,
      "city":"surat",
    },
    {
      "name":"tirthaa",
      "grid":3678,
      "age":18,
      "city":"mumbai",
    },
    {
      "name":"priyanshi",
      "grid":3679,
      "age":19,
      "city":"los angeles",
    },
    {
      "name":"khushi",
      "grid":3680,
      "age":18,
      "city":"surat",
    },
    {
      "name":"ragini",
      "grid":3681,
      "age":17,
      "city":"surat",
    },
    {
      "name":"sidhi",
      "grid":3682,
      "age":17,
      "city":"mumbai",
    },
    {
      "name":"jency",
      "grid":3683,
      "age":18,
      "city":"surat",
    },
    {
      "name":"nensi",
      "grid":3684,
      "age":19,
      "city":"surat",
    },
    {
      "name":"krimisha",
      "grid":3685,
      "age":19,
      "city":"surat",
    },
    {
      "name":"shreya",
      "grid":3686,
      "age":17,
      "city":"surat",
    },
    {
      "name":"pooja",
      "grid":3687,
      "age":17,
      "city":"surat",
    },
    {
      "name":"sakshi",
      "grid":3688,
      "age":20,
      "city":"mumbai",
    },
    {
      "name":"janvi",
      "grid":3689,
      "age":17,
      "city":"surat",
    },
    {
      "name":"sonali",
      "grid":3691,
      "age":20,
      "city":"mumbai",
    },
    {
      "name":"urvi",
      "grid":3692,
      "age":20,
      "city":"surat",
    },
    {
      "name":"misty",
      "grid":3693,
      "age":16,
      "city":"surat",
    },
    {
      "name":"jiya",
      "grid":3694,
      "age":17,
      "city":"mumbai",
    },
    {
      "name":"nisha",
      "grid":3695,
      "age":19,
      "city":"surat",
    },
  
  ];

  for(int i=0;i<20;i++)
  {
    print("${studentData[i]}");
  }
}
